organizer/urls.py
from django.urls import path
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

from . import views
from django.views.generic.base import RedirectView

app_name = 'organizer'
urlpatterns = [
    #path('', views.IndexView.as_view(), name='index'),
    path('calendar/', views.defaultCalendar, name='calendar'),
    path('calendar/<int:year>/<int:month>/', views.calendar, name='calendar-month'),
    path('calendar/goTo/', views.calendarGoTo, name='calendar-select'),
    path('classes/', views.ClassHomeView.as_view(), name='class-home'),
    path('classes/create/', views.ClassCreateView.as_view(), name='class-create'),
    path('classes/<pk>/', views.ClassDetailView.as_view(), name='class-detail'),
    path('classes/<pk>/join/', views.joinClass, name='class-join'),
    path('todo/', views.get_toDo, name='todo'),
    path('todo/list/', views.del_toDo, name='todo-list'),
    path('notes/', views.NoteHomeView.as_view(), name='note-home'),
    path('notes/upload/', views.UploadNoteView, name ='note-upload'),
    path('notes/changevisibility', views.ChangeNoteVisibility, name='note-change-visibility'),
    path('notes/all', views.NoteAllView.as_view(), name='note-all'),
    path('notes/<pk>/', views.NoteView.as_view(), name='note-edit'),
    path('notes/<pk>/delete/', views.deleteNote, name='note-delete'),

    #path('notes/all/major', views.NoteMajorView.as_view(), name='note-major'),

    # path('celerytest/', views.test, name="test"),
    # path('sendmail/', views.test_send_mail, name="sendmail"),
    # path('schedulemail/', views.schedule_mail, name="schedulemail")
    # path('classes/search', views.ClassSearchView.as_view(), name='search_result'),

    #added filters
    path('classes/index', views.ClassListView.as_view(), name='class-index'),
    path('notes/sortlist', views.NotesListView.as_view(), name='note-list'),

    # redirect URL to the home page
    path('', RedirectView.as_view(pattern_name='home', permanent=True), name='redirect-home')
] 


# celery -A project.celery worker --pool=solo -l info

# celery -A project beat -l INFO

project/urls.py
#https://stackoverflow.com/questions/2165865/django-queries-id-vs-pk
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView

from . import views

urlpatterns = [
    path('', views.redirect_HomeView, name='home'),
    path('admin/', admin.site.urls, name='admin'),
    path('organizer/', include('organizer.urls')),
    path('accounts/', include('allauth.urls')),
    path('logout', LogoutView.as_view(), name = 'logout'),
    path('edit-profile/<pk>/', views.ProfileEditView.as_view(), name='edit-profile'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

organizer/forms.py
from django import forms
from django.db.models import fields

from .models import ToDo, Note

from django.core.exceptions import ValidationError
from django.utils import timezone

from datetimewidget.widgets import DateTimeWidget

# https://pypi.org/project/django-datetime-widget2/
# https://docs.djangoproject.com/en/3.2/topics/forms/modelforms/
class toDoForm(forms.ModelForm):
    class Meta:
        model = ToDo
        exclude = ['user', 'created']
        fields = ('title', 'content', 'dueDate', 'remindTime')
        labels = {
            'title': 'Title:',
            'content': 'Description:',
            'dueDate': 'Due Date and Time:',
            'remindTime': 'Notification time before due (a reminder email will be sent):'
        }
        dateTimeOptions = {
            'format': 'mm/dd/yyyy HH:ii P',
            'autoclose': True,
            'showMeridian' : True,
            'minuteStep': 10,
            'todayHighlight': True,
        }
        widgets = {
            #Use localization and bootstrap 3
            'dueDate': DateTimeWidget(attrs={'id':"yourdatetimeid"}, usel10n=True, options=dateTimeOptions)
            #'dueDate': DateTimeWidget(options = dateTimeOptions)
        }

    # validate that the dueDate is at least remindTime min into the future, so that a reminder can be sent
    # https://stackoverflow.com/questions/43920328/data-returning-none-in-django-with-appended-select-field-in-js
    def clean(self):
        theDueDate = self.cleaned_data.get('dueDate')
        theRemindTime = self.cleaned_data.get('remindTime')
        #print((data - timezone.now()).total_seconds())
        if (theDueDate - timezone.now()).total_seconds()/60 <= theRemindTime:
            raise ValidationError("Set a valid time so your reminder can be sent!")

class UploadNoteForm(forms.ModelForm):
    class Meta:
        model = Note
        exclude = ['user']
        fields = ('title', 'file', 'theClass', 'isVisible')
        labels = {
            'title': 'Title:',
            'file': 'File',
            'theClass': 'Class',
            'isVisible': 'Visible to others in the class'
        }

organizer/views.py
from django.db.models import Q
from .filters import ClassFilter, NotesFilter, NotesAllFilter, MajorFilter
from django.http import HttpResponseRedirect, request
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic

from .models import Note, Calendar, Profile, ToDo, Classes
from .forms import toDoForm, UploadNoteForm
from .utils import Calendar
from django.utils import timezone
from django.shortcuts import redirect
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.core.exceptions import ObjectDoesNotExist
import os

#from django_celery_beat.models import PeriodicTask, CrontabSchedule
import json
import boto3


class IndexView(generic.TemplateView):
    template_name = 'organizer/index.html'

class CalendarView(generic.ListView):
    model = Calendar
    template_name = 'organizer/assignments/calendar.html'
    context_object_name = 'latest_thought_list'

    def get_queryset(self):
        return Calendar.objects.all()

class ClassHomeView(generic.TemplateView):
    template_name = 'organizer/class_home.html'

# https://docs.djangoproject.com/en/3.2/topics/db/examples/many_to_many/
class ClassDetailView(generic.DetailView):
    model = Classes
    template_name = 'organizer/class_detail.html'
    context_object_name = 'classes'

# https://docs.djangoproject.com/en/3.2/topics/http/urls/#topics-http-reversing-url-namespaces
class ClassCreateView(generic.CreateView):
    model = Classes
    template_name = 'organizer/class_create.html'
    fields = ['name', 'credits', 'code', 'courseNumber', 'year', 'professor']
    
    # success_url = reverse('organizer:class-home')
    success_url = '/organizer/classes/' # change to reverse() - doesn't work???

# https://docs.djangoproject.com/en/3.2/topics/db/queries/
# https://docs.djangoproject.com/en/3.2/topics/class-based-views/generic-display/
class ClassIndexView(generic.ListView):
    model = Classes
    template_name = 'organizer/class_index.html'
    context_object_name = 'classes'


def joinClass(request, pk):
    classToJoin = get_object_or_404(Classes,pk=pk)

    classToJoin.user.add(request.user)

    return redirect(reverse('organizer:class-home'))

class ToDoView(generic.ListView):
    model = ToDo
    template_name = 'organizer/todo.html'

class ToDoListView(generic.ListView):
    model = ToDo
    template_name = 'organizer/todo-list.html'

# https://stackoverflow.com/questions/18246326/how-do-i-set-user-field-in-form-to-the-currently-logged-in-user
# https://stackoverflow.com/questions/12848605/django-modelform-what-is-savecommit-false-used-for
# https://stackoverflow.com/questions/569468/django-multiple-models-in-one-template-using-forms/575133#575133
# https://stackoverflow.com/questions/20170062/displaying-django-form-validation-errors-for-modelforms
def get_toDo(request):
    if request.method == "POST":
        tD = toDoForm(request.POST)
        if tD.is_valid():
            theToDo = tD.save(commit=False) # commit=False so the User can be set to the current User automatically
            theToDo.user = User.objects.get(username=request.user.username) 
            theToDo.save()
            return HttpResponseRedirect(reverse('organizer:todo-list'))  # UPDATE TO SHOW CONFIRMATION
        else:
            return HttpResponse(tD.errors.values())  # error message - set it to display as a popup

    tD = toDoForm()
    return render(request, 'organizer/todo.html', {'form': tD})

# https://stackoverflow.com/questions/5895588/django-multivaluedictkeyerror-error-how-do-i-deal-with-it
# https://stackoverflow.com/questions/68113852/how-to-check-whether-the-checkbox-is-checked-in-django
# https://stackoverflow.com/questions/6223149/django-post-checkbox-data
def del_toDo(request):
    if request.user.is_authenticated:
        todos = ToDo.objects.filter(user=request.user)

        if request.method == "POST":
            todo = toDoForm(request.POST)
            #if "toDoDelete" in request.POST: 
            if "checkedbox" in request.POST:  # handles MultiValueDictKeyError if nothing is selected when attempting to delete
                checkedlist = request.POST.getlist('checkedbox')
                for todo_id in checkedlist:
                    #print(todo_id)
                    todo = ToDo.objects.get(id=todo_id)
                    todo.delete()
                return HttpResponseRedirect(reverse('organizer:todo-list'))

            else:
                pass # IMPLEMENT POPUP WARNING HERE!!!!!
        else:
            todo = toDoForm()

        return render(request, 'organizer/todo-list.html', {'objs': todos, 'form': todo})
    else:
        return HttpResponseRedirect(reverse('home'))


# https://docs.djangoproject.com/en/3.2/topics/http/file-uploads/
def UploadNoteView(request):
    if request.method == 'POST':
        form = UploadNoteForm(request.POST, request.FILES)
        if form.is_valid():
            theNote = form.save(commit=False)
            theNote.user = User.objects.get(username=request.user.username)
            theNote.save()
            return redirect(reverse('organizer:note-home')) # UPDATE TO DISPLAY SUCCESS MESSAGE, REDIRECT
    else:
        form = UploadNoteForm()
        context = {
            'form':form,
        }
    return render(request, 'organizer/note-upload.html', context)

def ChangeNoteVisibility(request):
    if request.method == "POST": 
            if "checkedbox" in request.POST:  # handles MultiValueDictKeyError if nothing is selected when attempting to delete
                checkedlist = request.POST.getlist('checkedbox')
                for note_id in checkedlist:
                    note = Note.objects.get(id=note_id)
                    note.isVisible = (not note.isVisible)
                    note.save()
                    return HttpResponseRedirect(reverse('organizer:note-home'))
            else:
                pass # IMPLEMENT POPUP WARNING HERE!!!!!

    return redirect(reverse('organizer:note-home'))        

class NoteHomeView(generic.TemplateView):
    template_name = 'organizer/note-home.html'

class NoteView(generic.DetailView):
    model = Note
    template_name = 'organizer/note-detail.html'
    context_object_name = 'note'

def deleteNote(request, pk):
    note = get_object_or_404(Note, pk=pk)
    note.delete()
    return redirect(reverse('organizer:note-home'))

class NoteAllView(generic.ListView):
    model = Note
    template_name = 'organizer/note-all.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = NotesAllFilter(self.request.GET, queryset=self.get_queryset())
        return context

class NoteMajorView(generic.ListView):
    model = Note
    template_name = 'organizer/note-major.html'

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(user__profile__major=self.request.user.profile.major)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = MajorFilter(self.request.GET, queryset=self.get_queryset())
        return context

#def download_file(file_name):
    # s3 = boto3.client('s3')
    # s3.download_file('a18-organizer-new', file_name, 'media/' + file_name)

    # return redirect('media/' + file_name)

# https://www.huiwenteo.com/normal/2018/07/24/django-calendar.html
def calendar(request, year, month):

    if request.user.is_authenticated:
        # cal = HTMLCalendar().formatmonth(year, month)
        cal = Calendar(year, month, request.user).formatmonth(withyear=True)

        next_year = year
        previous_year = year

        # jump to previous year
        if(month - 1 < 1):
            prev_month = 12
            previous_year = year - 1
        else:
            prev_month = month - 1
            previous_year = year

        # jump to next year
        if(month + 1 > 12):
            next_month = 1
            next_year = year + 1
        else:
            next_month = month + 1
            next_year = year

        return render(request, 'organizer/assignments/calendar.html',
                    {
                        'prev_month': prev_month,
                        'next_month': next_month,
                        'next_year': next_year,
                        'previous_year': previous_year,
                        'month': month,
                        'cal': cal,
                    })
    else:
        return HttpResponseRedirect(reverse('home'))

# https://www.huiwenteo.com/normal/2018/07/24/django-calendar.html
def defaultCalendar(request):
    if request.user.is_authenticated:
        today = timezone.now()
        cal = Calendar(today.year, today.month, request.user).formatmonth(withyear=True)

        next_year = today.year
        previous_year = today.year

        # jump to previous year
        if(today.month - 1 < 1):
            prev_month = 12
            previous_year = today.year - 1
        else:
            prev_month = today.month - 1

        # jump to next year
        if(today.month + 1 > 12):
            next_month = 1
            next_year = today.year + 1
        else:
            next_month = today.month + 1

        return render(request, 'organizer/assignments/calendar.html',
                    {
                        'next_year': next_year,
                        'previous_year': previous_year,
                        'month': today.month,
                        'prev_month': prev_month,
                        'next_month': next_month,
                        "cal": cal,
                    })
    else:
        return HttpResponseRedirect(reverse('home'))


organizer/templates/organizer/assignments/calendar.html
{# Load the tag library #}
{% load bootstrap5 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% load static %}
{% load socialaccount %}


<!DOCTYPE html>
<html>

<link rel="stylesheet" type="text/css" href="{% static 'organizer/style.css' %}">


<style type="text/css">
    table {
        border: 1px solid black;
        background-color:white;
    }
    th {
        border: 1px solid black;
        text-align: center;
        font-size: 20px;
    }
    td {
        border: 1px solid black;
        padding: 5px;
        width: 150px;
        height: 150px;
        vertical-align: top;
        background-color:white;
    }
    fieldset {
        padding: 10px;
        background-color:#e3f2fd;
   }
   h2 {
        text-align:center;
        background-color: white;
   }

   label {
      font-weight: bold;
      font-size: 17px;
   }
   /* 
  nav bar 
  https://getbootstrap.com/docs/4.0/components/navbar/ 
  transparent
  https://mdbootstrap.com/docs/standard/navigation/navbar/
  footer
  https://codepen.io/mdbootstrap/pen/YEPERj?editors=1000 
  background image
  https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Backgrounds_and_Borders/Resizing_background_images
  rotunda image
  https://www.rbiva.com/project/university-of-virginia-rotunda/
  */ 
</style>


{% if user.is_authenticated %}
<nav class="navbar navbar-expand-lg navbar-dark shadow-5-strong">
  <div class="container-fluid">
      <!-- https://stackoverflow.com/questions/3710360/padding-on-div-border -->
    <a class="navbar-brand" href={% url 'home' %}>Hoos Organized</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Classes
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarPolls">
            <li><a class="dropdown-item" href={% url 'organizer:class-home' %}>Class Dashboard</a></li>
            <li><a class="dropdown-item" href={% url 'organizer:class-index' %}>Class Index</a></li>
            <li><a class="dropdown-item" href={% url 'organizer:class-create' %}>Create a Class</a></li>
          </ul>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Calendar & To Dos
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarPolls">
            <li><a class="dropdown-item" href={% url 'organizer:calendar' %}>Calendar</a></li>
            <li><a class="dropdown-item" href={% url 'organizer:todo-list' %}>To Do List</a></li>
            <li><a class="dropdown-item" href={% url 'organizer:todo' %}>Create a To Do</a></li>
          </ul>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Notes
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarPolls">
            <li><a class="dropdown-item" href={% url 'organizer:note-home' %}>My Notes</a></li>
            <li><a class="dropdown-item" href={% url 'organizer:note-all' %}>All Notes</a></li>
            <li><a class="dropdown-item" href={% url 'organizer:note-upload' %}>Upload Notes</a></li>
          </ul>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Settings
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarPolls">
            <li><a class="dropdown-item" href={% url 'edit-profile' user.profile.id %}>Edit Profile</a></li>
            <li><a class="dropdown-item" href={% url 'logout' %}>Log Out</a></li>
          </ul>
        </li>

    </div>
  </div>
</nav>


<body>
  <h2 style="background-color:#008CBA; border-radius:6px"><a style="color:white">Calendar</a></h2>

<!--  Initialize Calendar -->
<fieldset>
  <br>
    <center>
    {{ cal|safe }}
    </center>
</fieldset>

<!--Add Previous & Next Buttons-->
<fieldset layout="horizontal">
  <hr>
  <center>
    <a href="{% url 'organizer:calendar-month' previous_year prev_month %}" class="btn btn-primary">Previous Month</a>&nbsp;
    <a href="{% url 'organizer:calendar' %}" class="btn btn-primary">Current Month</a>&nbsp;
    <a href="{% url 'organizer:calendar-month' next_year next_month %}" class="btn btn-primary">Next Month</a>

    <div style="line-height:12px;">
    <br>
    </div>

    <!--    Go to Specific Month & Year -->
    <!--    https://www.w3schools.com/tags/tag_select.asp-->
    <form action="{% url 'organizer:calendar-select' %}" method="post">
      {% csrf_token %}
      <label for="select_month">Select a Month:</label>
      <select name="select_month" id="select_month" >
        <option value="none">--</option>
        <option value="1">January</option>
        <option value="2">February</option>
        <option value="3">March</option>
        <option value="4">April</option>
        <option value="5">May</option>
        <option value="6">June</option>
        <option value="7">July</option>
        <option value="8">August</option>
        <option value="9">September</option>
        <option value="10">October</option>
        <option value="11">November</option>
        <option value="12">December</option>
      </select>&nbsp;

      <label for="select_year">Enter Year:</label>
      <input type="text" name="select_year" id="select_year">&nbsp;&nbsp;&nbsp;

      <input type="submit" class="btn btn-primary" value="Go to Month">

    </form>
  </center>
</fieldset>
<br><br>
<br><br>



<body>
    <div class="footer-clean">
        <footer style="background-color:#e9d8f2">
            <div class="container">
                <div class="row justify-content-center">
                    
                    <div class="container">
                            <div class="row">

                                <!--First column-->
                                <div class="col-md-4">
                                    <h5 class="title mb-4 mt-3 font-bold">A-18</h5>
                                    <p>Choong-Hyun Kim | Jade Burns | Julian Lee | Palash Shah | Sarah Gould</p>
                                </div>
                                <!--/.First column-->

                                <hr class="clearfix w-100 d-md-none">

                                <!--Second column-->
                                <div class="col-md-2 mx-auto">
                                    <h5 class="title mb-4 mt-3 font-bold">Classes</h5>
                                    <ul class="list-unstyled mb-0">
                                        <li><a href={% url 'organizer:class-home' %}>Class Dashboard</a></li>
                                        <li><a href={% url 'organizer:class-index' %}>Class Index</a></li>
                                        <li><a href={% url 'organizer:class-create' %}>Create a Class</a></li>
                                    </ul>
                                </div>
                                <!--/.Second column-->

                                <hr class="clearfix w-100 d-md-none">

                                <!--Third column-->
                                <div class="col-md-2 mx-auto">
                                    <h5 class="title mb-4 mt-3 font-bold">Calendar & To Dos</h5>
                                    <ul class="list-unstyled mb-0">
                                        <li><a href={% url 'organizer:calendar' %}>Calendar</a></li>
                                        <li><a href={% url 'organizer:todo-list' %}>To Do List</a></li>
                                        <li><a href={% url 'organizer:todo' %}>Create a To Do</a></li>
                                    </ul>
                                </div>
                                <!--/.Third column-->

                                <hr class="clearfix w-100 d-md-none">

                                <!--Fourth column-->
                                <div class="col-md-2 mx-auto">
                                    <h5 class="title mb-4 mt-3 font-bold ">Notes</h5>
                                    <ul class="list-unstyled mb-0">
                                        <li><a href={% url 'organizer:note-home' %}> My Notes</li>
                                          <li><a href={% url 'organizer:note-all' %}> All Notes</li>
                                        <li><a href={% url 'organizer:note-upload' %}>Upload Notes</li>
                                    </ul>
                                </div>
                                <!--/.Fourth column-->
                            </div>
                          </div>
              
                </div>
            </div>
        </footer>
    </div>
</body>

{% else %}
<body>
  <section class="h-100">
  <header class="container h-20">
    <div class="d-flex align-items-center justify-content-center h-100">
      <div class="d-flex flex-column">
        <div class ="header">
          <h1 style="color:#ff8c00">Hoos Organized</h1>
        </div>
          <a style="background-color:orange" href="{% provider_login_url 'google' %}">Login With Google</a>
      </div>
    </div>

</div>
</header>
</section>
</body>


  <style>
    h1 {
        text-align: center;
        background-color: white;
        padding: 6px;
        font-family:'Cursive', lucida handwriting;
        font-size: +40;
    }
    a:link {
      font-family:'Cursive', lucida handwriting;
      color: #ff8c00;
      text-align: center;
      background-color: white;
      text-decoration: none;
      font-size: +20;
    }
    a:hover {
      font-family:'Cursive', lucida handwriting;
      color: #ff8c00;
      text-align: center;
      background-color: white;
      text-decoration: none;
      font-size: +20;
    }
  </style>

{% endif %}



</html>