organizer/urls.py
from django.urls import path
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

from . import views
from django.views.generic.base import RedirectView

app_name = 'organizer'
urlpatterns = [
    #path('', views.IndexView.as_view(), name='index'),
    path('calendar/', views.defaultCalendar, name='calendar'),
    path('calendar/<int:year>/<int:month>/', views.calendar, name='calendar-month'),
    path('calendar/goTo/', views.calendarGoTo, name='calendar-select'),
    path('classes/', views.ClassHomeView.as_view(), name='class-home'),
    path('classes/create/', views.ClassCreateView.as_view(), name='class-create'),
    path('classes/<pk>/', views.ClassDetailView.as_view(), name='class-detail'),
    path('classes/<pk>/join/', views.joinClass, name='class-join'),
    path('todo/', views.get_toDo, name='todo'),
    path('todo/list/', views.del_toDo, name='todo-list'),
    path('notes/', views.NoteHomeView.as_view(), name='note-home'),
    path('notes/upload/', views.UploadNoteView, name ='note-upload'),
    path('notes/changevisibility', views.ChangeNoteVisibility, name='note-change-visibility'),
    path('notes/all', views.NoteAllView.as_view(), name='note-all'),
    path('notes/<pk>/', views.NoteView.as_view(), name='note-edit'),
    path('notes/<pk>/delete/', views.deleteNote, name='note-delete'),

    #path('notes/all/major', views.NoteMajorView.as_view(), name='note-major'),

    # path('celerytest/', views.test, name="test"),
    # path('sendmail/', views.test_send_mail, name="sendmail"),
    # path('schedulemail/', views.schedule_mail, name="schedulemail")
    # path('classes/search', views.ClassSearchView.as_view(), name='search_result'),

    #added filters
    path('classes/index', views.ClassListView.as_view(), name='class-index'),
    path('notes/sortlist', views.NotesListView.as_view(), name='note-list'),

    # redirect URL to the home page
    path('', RedirectView.as_view(pattern_name='home', permanent=True), name='redirect-home')
] 


# celery -A project.celery worker --pool=solo -l info

# celery -A project beat -l INFO

project/urls.py
#https://stackoverflow.com/questions/2165865/django-queries-id-vs-pk
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView

from . import views

urlpatterns = [
    path('', views.redirect_HomeView, name='home'),
    path('admin/', admin.site.urls, name='admin'),
    path('organizer/', include('organizer.urls')),
    path('accounts/', include('allauth.urls')),
    path('logout', LogoutView.as_view(), name = 'logout'),
    path('edit-profile/<pk>/', views.ProfileEditView.as_view(), name='edit-profile'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/edit-profile.html
{# Load the tag library #}
{% load bootstrap5 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% load static %}
{% load socialaccount %}

<!DOCTYPE html>
<html>

<link rel="stylesheet" type="text/css" href="{% static 'organizer/style.css' %}">

<style type="text/css">
   html {
    overflow-y: hidden;
   }

   h2 {
        text-align:center;
        background-color: white;
   }
   fieldset {
        padding: 20px;
        background-color:#e3f2fd;
   }
   /* 
  image upload
  https://docs.djangoproject.com/en/3.2/howto/static-files/
  nav bar 
  https://getbootstrap.com/docs/4.0/components/navbar/ 
  transparent
  https://mdbootstrap.com/docs/standard/navigation/navbar/
  footer
  https://codepen.io/mdbootstrap/pen/YEPERj?editors=1000 
  background image
  https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Backgrounds_and_Borders/Resizing_background_images
  rotunda image
  https://www.rbiva.com/project/university-of-virginia-rotunda/
  centering content
  https://stackoverflow.com/questions/18777235/center-content-in-responsive-bootstrap-navbar
  */ 
</style>


{% if user.is_authenticated %}
<nav class="navbar navbar-expand-lg navbar-dark shadow-5-strong">
  <div class="container-fluid">
    <a class="navbar-brand" href={% url 'home' %}>Hoos Organized</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Classes
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarPolls">
            <li><a class="dropdown-item" href={% url 'organizer:class-home' %}>Class Dashboard</a></li>
            <li><a class="dropdown-item" href={% url 'organizer:class-index' %}>Class Index</a></li>
            <li><a class="dropdown-item" href={% url 'organizer:class-create' %}>Create a Class</a></li>
          </ul>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Calendar & To Dos
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarPolls">
            <li><a class="dropdown-item" href={% url 'organizer:calendar' %}>Calendar</a></li>
            <li><a class="dropdown-item" href={% url 'organizer:todo-list' %}>To Do List</a></li>
            <li><a class="dropdown-item" href={% url 'organizer:todo' %}>Create a To Do</a></li>
          </ul>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Notes
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarPolls">
            <li><a class="dropdown-item" href={% url 'organizer:note-home' %}>My Notes</a></li>
            <li><a class="dropdown-item" href={% url 'organizer:note-all' %}>All Notes</a></li>
            <li><a class="dropdown-item" href={% url 'organizer:note-upload' %}>Upload Notes</a></li>
          </ul>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Settings
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarPolls">
            <li><a class="dropdown-item" href={% url 'edit-profile' user.profile.id %}>Edit Profile</a></li>
            <li><a class="dropdown-item" href={% url 'logout' %}>Log Out</a></li>
          </ul>
        </li>

    </div>
  </div>
</nav>

{% if profile.user == user %}

<body>
<section class="h-100">
  <header class="container h-70">
    <div class="d-flex justify-content-center h-100">
      <div class="d-flex flex-column">
<form method="post"> 
    {% csrf_token %} 

    <h2 style="background-color:#008CBA; border-radius:6px"><a style="color:white">{{ user.first_name }}'s Profile</a></h2>
    <fieldset style="border-radius:6px; color:black">
    {% if user.profile.computingID == '' %}
        <div style="color:#ff8c00; text-align:center; font-size:17px; font-weight:500;">In order to access our features, please fill out your information!</div>
    {% endif %}
    <fieldset>
    {{ form.as_p }} 
    <br>
    
</form> 
<div style="text-align:center;">
    <input style="background-color:#008CBA; border-radius:6px; color:white; font-size:17px;" type="submit" value="Save">
    </div>

</div>
</div>
</header>
</section>
<body>

{% else %}
<b>You are not authorized to edit this profile.</b>
{% endif %}

<body>
  <div class="fixed-bottom">
    <div class="footer-clean">
        <footer style="background-color:#e9d8f2">
            <div class="container">
                <div class="row justify-content-center">
                    
                    <div class="container">
                            <div class="row">

                                <!--First column-->
                                <div class="col-md-4">
                                    <h5 class="title mb-4 mt-3 font-bold">A-18</h5>
                                    <p>Choong-Hyun Kim | Jade Burns | Julian Lee | Palash Shah | Sarah Gould</p>
                                </div>
                                <!--/.First column-->

                                <hr class="clearfix w-100 d-md-none">

                                <!--Second column-->
                                <div class="col-md-2 mx-auto">
                                    <h5 class="title mb-4 mt-3 font-bold">Classes</h5>
                                    <ul class="list-unstyled mb-0">
                                        <li><a href={% url 'organizer:class-home' %}>Class Dashboard</a></li>
                                        <li><a href={% url 'organizer:class-index' %}>Class Index</a></li>
                                        <li><a href={% url 'organizer:class-create' %}>Create a Class</a></li>
                                    </ul>
                                </div>
                                <!--/.Second column-->

                                <hr class="clearfix w-100 d-md-none">

                                <!--Third column-->
                                <div class="col-md-2 mx-auto">
                                    <h5 class="title mb-4 mt-3 font-bold">Calendar & To Dos</h5>
                                    <ul class="list-unstyled mb-0">
                                        <li><a href={% url 'organizer:calendar' %}>Calendar</a></li>
                                        <li><a href={% url 'organizer:todo-list' %}>To Do List</a></li>
                                        <li><a href={% url 'organizer:todo' %}>Create a To Do</a></li>
                                    </ul>
                                </div>
                                <!--/.Third column-->

                                <hr class="clearfix w-100 d-md-none">

                                <!--Fourth column-->
                                <div class="col-md-2 mx-auto">
                                    <h5 class="title mb-4 mt-3 font-bold ">Notes</h5>
                                    <ul class="list-unstyled mb-0">
                                        <li><a href={% url 'organizer:note-home' %}> My Notes</li>
                                          <li><a href={% url 'organizer:note-all' %}> All Notes</li>
                                        <li><a href={% url 'organizer:note-upload' %}>Upload Notes</li>
                                    </ul>
                                </div>
                                <!--/.Fourth column-->
                            </div>
                          </div>
              
                </div>
            </div>
        </footer>
    </div>
  </div>
</body>

{% else %}
<body>
  <section class="h-100">
  <header class="container h-20">
    <div class="d-flex align-items-center justify-content-center h-100">
      <div class="d-flex flex-column">
        <div class ="header">
          <h1 style="color:#ff8c00">Hoos Organized</h1>
          <fieldset>
        </div>
          <a style="background-color:orange" href="{% provider_login_url 'google' %}">Login With Google</a>
      </div>
      <fieldset>
    </div>

</div>
</header>
</section>
</body>


  <style>
    h1 {
        text-align: center;
        background-color: white;
        padding: 6px;
        font-family:'Cursive', lucida handwriting;
        font-size: +40;
    }
    a:link {
      font-family:'Cursive', lucida handwriting;
      color: #ff8c00;
      text-align: center;
      background-color: white;
      text-decoration: none;
      font-size: +20;
    }
    a:hover {
      font-family:'Cursive', lucida handwriting;
      color: #ff8c00;
      text-align: center;
      background-color: white;
      text-decoration: none;
      font-size: +20;
    }
  </style>

{% endif %}

</html>

templates/index.html
{# Load the tag library #}
{% load bootstrap5 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% load static %}
{% load socialaccount %}

<!DOCTYPE html>
<html>

<link rel="stylesheet" type="text/css" href="{% static 'organizer/style.css' %}">
<style type="text/css">
   h1 {
        text-align:center;
        background-color: white;
        font-family:'Cursive', lucida handwriting;
        padding-right: 10px;
        padding-left: 10px;
   }
   h2 {
        text-align:center;
        font-family:'Cursive', lucida handwriting;
   }
   fieldset {
        text-align:center;
        background-color:#e3f2fd;
        font-family:'Cursive', lucida handwriting;
        font-size: +25;
   }
   /* 
  nav bar 
  https://getbootstrap.com/docs/4.0/components/navbar/ 
  transparent
  https://mdbootstrap.com/docs/standard/navigation/navbar/
  footer
  https://codepen.io/mdbootstrap/pen/YEPERj?editors=1000 
  background image
  https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Backgrounds_and_Borders/Resizing_background_images
  rotunda image
  https://www.rbiva.com/project/university-of-virginia-rotunda/
  */ 
</style>





{% if user.is_authenticated %}
<nav class="navbar navbar-expand-lg navbar-dark shadow-5-strong">
  <div class="container-fluid">
    <a class="navbar-brand" href={% url 'home' %}>Hoos Organized</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Classes
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarPolls">
            <li><a class="dropdown-item" href={% url 'organizer:class-home' %}>Class Dashboard</a></li>
            <li><a class="dropdown-item" href={% url 'organizer:class-index' %}>Class Index</a></li>
            <li><a class="dropdown-item" href={% url 'organizer:class-create' %}>Create a Class</a></li>
          </ul>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Calendar & To Dos
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarPolls">
            <li><a class="dropdown-item" href={% url 'organizer:calendar' %}>Calendar</a></li>
            <li><a class="dropdown-item" href={% url 'organizer:todo-list' %}>To Do List</a></li>
            <li><a class="dropdown-item" href={% url 'organizer:todo' %}>Create a To Do</a></li>
          </ul>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Notes
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarPolls">
            <li><a class="dropdown-item" href={% url 'organizer:note-home' %}>My Notes</a></li>
            <li><a class="dropdown-item" href={% url 'organizer:note-all' %}>All Notes</a></li>
            <li><a class="dropdown-item" href={% url 'organizer:note-upload' %}>Upload Notes</a></li>
          </ul>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Settings
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarPolls">
            <li><a class="dropdown-item" href={% url 'edit-profile' user.profile.id %}>Edit Profile</a></li>
            <li><a class="dropdown-item" href={% url 'logout' %}>Log Out</a></li>
          </ul>
        </li>

    </div>
  </div>
</nav>

        
<body>
  <section class="h-50">
  <header class="container h-20">
    <div class="d-flex align-items-center justify-content-center h-75">
      <div class="d-flex flex-column">
        <div class ="header">
          <h1 style="color:#ff8c00; border-radius:6px">Hoos Organized</h1>

        </div>
          <h2 style="background-color:#008CBA; border-radius:6px"><a style="color:white">Welcome, {{ user.first_name }}!</a></h2>
        </div>
    </div>

</div>
</header>
</section>
</body>


<body>
  <div class="fixed-bottom">
    <div class="footer-clean">
        <footer style="background-color:#e9d8f2">
            <div class="container">
                <div class="row justify-content-center">
                    
                    <div class="container">
                            <div class="row">

                                <!--First column-->
                                <div class="col-md-4">
                                    <h5 class="title mb-4 mt-3 font-bold">A-18</h5>
                                    <p>Choong-Hyun Kim | Jade Burns | Julian Lee | Palash Shah | Sarah Gould</p>
                                </div>
                                <!--/.First column-->

                                <hr class="clearfix w-100 d-md-none">

                                <!--Second column-->
                                <div class="col-md-2 mx-auto">
                                    <h5 class="title mb-4 mt-3 font-bold">Classes</h5>
                                    <ul class="list-unstyled mb-0">
                                        <li><a href={% url 'organizer:class-home' %}>Class Dashboard</a></li>
                                        <li><a href={% url 'organizer:class-index' %}>Class Index</a></li>
                                        <li><a href={% url 'organizer:class-create' %}>Create a Class</a></li>
                                    </ul>
                                </div>
                                <!--/.Second column-->

                                <hr class="clearfix w-100 d-md-none">

                                <!--Third column-->
                                <div class="col-md-2 mx-auto">
                                    <h5 class="title mb-4 mt-3 font-bold">Calendar & To Dos</h5>
                                    <ul class="list-unstyled mb-0">
                                        <li><a href={% url 'organizer:calendar' %}>Calendar</a></li>
                                        <li><a href={% url 'organizer:todo-list' %}>To Do List</a></li>
                                        <li><a href={% url 'organizer:todo' %}>Create a To Do</a></li>
                                    </ul>
                                </div>
                                <!--/.Third column-->

                                <hr class="clearfix w-100 d-md-none">

                                <!--Fourth column-->
                                <div class="col-md-2 mx-auto">
                                    <h5 class="title mb-4 mt-3 font-bold ">Notes</h5>
                                    <ul class="list-unstyled mb-0">
                                        <li><a href={% url 'organizer:note-home' %}> My Notes</li>
                                          <li><a href={% url 'organizer:note-all' %}> All Notes</li>
                                        <li><a href={% url 'organizer:note-upload' %}>Upload Notes</li>
                                    </ul>
                                </div>
                                <!--/.Fourth column-->
                            </div>
                          </div>
              
                </div>
            </div>
        </footer>
    </div>
  </div>
</body>



{% else %}
<body>
  <section class="h-100">
  <header class="container h-20">
    <div class="d-flex align-items-center justify-content-center h-100">
      <div class="d-flex flex-column">
        <div class ="header">
          <h1 style="color:#ff8c00; border-radius:6px">Hoos Organized</h1>
        </div>
          <a style="background-color:#008CBA; border-radius:6px; color:white;" href="{% provider_login_url 'google' %}">Login With Google</a>
      </div>
    </div>

</div>
</header>
</section>
</body>


  <style>
    h1 {
        text-align: center;
        background-color: white;
        padding: 6px;
        font-family:'Cursive', lucida handwriting;
        font-size: +40;
    }
    a:link {
      font-family:'Cursive', lucida handwriting;
      color: #ff8c00;
      text-align: center;
      background-color: white;
      text-decoration: none;
      font-size: +20;
    }
    a:hover {
      font-family:'Cursive', lucida handwriting;
      color: #ff8c00;
      text-align: center;
      background-color: white;
      text-decoration: none;
      font-size: +20;
    }
  </style>

{% endif %}

</html>